### ISSUE TITLE
High level requirements doubts

### ISSUE THREAD

**Issue by ChristianFN2** [Arquisoft/wiq_en1a#12]
![IMG-20240209-WA0005](https://github.com/Arquisoft/wiq_en1a/assets/157963970/866691c7-3daf-4367-975b-95d5e092fab8)

We were talking in the team about what the requirements in the picture above implied and meant and, to be sure about the correct answer, I am writing to ask if this means that the client must have access to these APIs (separately from the main app system) to visualize the users that have played the game and the generated questions' information, or if the user itself also has access to those functionallities. 

I incline to the first answer, but maybe it is the second one or a completely different one.

To illustrate what I mean, I also attached a context diagram with the parts I am unsure about drawn in pencil:

![IMG20240209214740](https://github.com/Arquisoft/wiq_en1a/assets/157963970/667453df-59ca-49d1-a3d3-249152c0c58f)

**Comment by pglez82** [comment]
In my opinion these requirements mean that there must be a separate API than handles users and another for handling questions. Apart from that, I think that the two options that you write are possible (or even others). The only thing is that these two functionalities must be implemented in two different services and accessed with two different APIs, the rest is up to you and the architecture that you choose.

**Comment by ChristianFN2** [comment]
We were thinking again about the APIs and I think we still misunderstood the implications of the requirements:

We thought that we had to make the APIs to show the data of the users and questions to the user (in the front end), but I think I understood now that the only implication of these two requirements is that we have to have, internally, an API for the management of users and another one for the management of questions, both used by the main system of the game.
So we do not need to show that information to the user (as for the requirements of the assignment), right? @pglez82

**Comment by pglez82** [comment]
In my opinion you need to show this kind of information to the user. There is this other requirement:

- Users will be able to register to the system and obtain the historical data from their participation: number of games, questions passed and failed, times, etc ..

So in my opinion there should be an API that handles the user information and this API will be used by the frontend.

**Comment by ChristianFN2** [comment]
Yes, we are aware of the requirement you mention. So, in this case, I understand that the user API would be in charge of managing both users and their scores (Storing them and showing them to the user when needed) and the questions API would be responsible for constructing the questions and showing them. 

The main concern we have is if we have to store and show the literal questions or just their statistics for the requirement of the historical data.

**Comment by pglez82** [comment]
In my opinion there is no specific requirement of storing the literal questions that are shown to the user (of course you can still do it if you think the functionality that you will create will need them)

**Comment by andrrsin** [comment]
I will close the issue, for th emoment to keep the board clean. After that if we need to reopen it will do it again!
