### ISSUE TITLE
Restart of E2E tests

### ISSUE THREAD

**Issue by andrrsin** [Arquisoft/wiq_en1a#128]
Since the beggining the e2e tests have been failing. Now they won't even start to test and they will fail. I propose resarting all over again and do some basic tests. I think that it would be the decision that wold give us less technical debt.

**Comment by andrrsin** [comment]
I have detected t eproblem is due to the library called `mongodb-memory-server`. I suggest trying to change the way to create a new mongodb database ust going to the URL and instead of using our current one, changing it for a tesing one. If this solves the problem we can remain with them

**Comment by ChristianFN2** [comment]
Yes, in case there are still problems it is better to start again or think of a solution quickly, because we do not have that much time left and we need these tests.
