### ISSUE TITLE
First Delivery Report 

### ISSUE THREAD

**Issue by uo287841** [Arquisoft/wiq_en1a#18]
## Week 1 Updates:
- Wrote the [Meeting 02](https://github.com/Arquisoft/wiq_en1a/wiki/Meeting-05-02-2024)
- Opened an issue #4 in order to save in one place links or info that can be interesting for the web development

## Week 2 Updates:
- Generate documentation for point 1.3, 2 and 9

**Comment by UO287621** [comment]
Links are broken
