### ISSUE TITLE
Front-End

### ISSUE THREAD

**Issue by adriiglz** [Arquisoft/wiq_en1a#27]
Issues related to the front end development

**Comment by UO287621** [comment]
regarding the new pull request #42 , it would be a good idea to modify the design of the login page so users are able to register from the login page. As well as modifying the navbar once the user has been logged so the login button is no longer displayed. Instead, the name of the user could be displayed in the navbar, for example

@andrrsin thought you would be interested in this as you were developing the new login and register functionallitites

**Comment by andrrsin** [comment]
Yes of course I'll get to it as soon as I can!!!
