### ISSUE TITLE
Data Base Structure

### ISSUE THREAD

**Issue by uo287841** [Arquisoft/wiq_en1a#30]
<img width="487" alt="Captura de pantalla 2024-02-24 185656" src="https://github.com/Arquisoft/wiq_en1a/assets/124190755/02309c1e-da95-42e2-9398-fecfc450e311">

I want to know your opinions on the Database. I still feel that there are some entities missing, but I don't know which:

- Client: Users that have an account on the Web application, their username is unique.

- WIQ_Server: Is used to save information about the game and the user that requested the game.

- WIQ_Game: Manages the games, selects the number of questions, and saves extra information.

- WIQ_Questions: Connects the Question to the WIQ_Game.

- Question: Contains general information about the question asked; it only saves the right answer and the number of wrong answers to know how many to generate.

Additionally, I would like to know your opinion about the relationship I used to link Game with Questions. I think this is a better approach because we can reuse the questions. In the case of using a many-to-one relation between questions and games, we would need to save an instance of the game_id inside questions, and we wouldn't be able to reuse them. Let me know if you think of a better approach to this.

I have also thought about this approach:
<img width="454" alt="bd2" src="https://github.com/Arquisoft/wiq_en1a/assets/124190755/6c272b2b-a264-4e5c-a94e-34dde456d249">

**Comment by ChristianFN2** [comment]
For using wikidata we do not need an api key (from what I saw and tested).

I think we do not need so many tables as the data we are storing has few relationships. I would identify as tables: User (user_id, username, password), UserStats(1 per user, includes global game statistics for a user), Score(Stats for a particular game, makes reference to a user with its user_id). We should not need to store the specific questions for the basic funcionallity (requirements)

**Comment by andrrsin** [comment]
Hey, I'm seeing we're talking like we were working in SQL, Remember with MongoDB we work on JSON tables. This means we can have more complex data stored. I think the proposal of Christian for the moment can even be simplified. 

We can have User(User + UserStats joined), then we can have Game that would be Score and we can add an array being question in case we want to store the data of the game)

**Comment by UO287621** [comment]
Andres' approach looks optimum
