### ISSUE TITLE
User Collection

### ISSUE THREAD

**Issue by uo287841** [Arquisoft/wiq_en1a#33]
Should we include the user global soce inside the same user model or keep it in a separate collection?

**Comment by UO287621** [comment]
I guess you mean user's score. I see two options:
- Keep the collection of ids of answered questions by the user inside the User document
- Create a new document that includes the id of the user and the collection of ids of the questions answered by the user

In both cases we could include a total score based on the number of correct answers

**Comment by adriiglz** [comment]
I updated some info in #28 which covers this issue as well
