### ISSUE TITLE
Question generation - First category of questions prepared

### ISSUE THREAD

**Issue by ChristianFN2** [Arquisoft/wiq_en1a#34]
This first category consists on retrieving from wikidata several countries with their flag images, choosing 4 of them at random for the question and 1 of them to be the correct one, so the player has to choose it to gain the point.

As we do not have the game view operative yet, I performed the tests appart from the project again (with a simple view to visualize the results), so I will share the code I used and comment what the service will really be retrieving when we have the view operative (my idea about it)

This is the main javascript file:

```
import { WBK } from './node_modules/wikibase-sdk/dist/src/wikibase-sdk.js'

const wbk = WBK({
  instance: 'https://www.wikidata.org',
  sparqlEndpoint: 'https://query.wikidata.org/sparql' // Required to use `sparqlQuery` and `getReverseClaims` functions, optional otherwise
})

class WIQ_API{
  async getCountriesWithImages() {
    const countriesNum = 100 

    const headers = new Headers();
    headers.append('User-Agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'
    +' AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36');

    const sparql = `SELECT ?país ?paísLabel ?imagen_de_la_bandera WHERE {
      SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
      ?país wdt:P31 wd:Q6256.
      OPTIONAL { ?país wdt:P41 ?imagen_de_la_bandera. }
    }
    LIMIT `+countriesNum

    var url = wbk.sparqlQuery(sparql);

    const response = await fetch(url, { headers });
    const data = await response.json()

    const chosenNums = [];
    const numOfChosen = 4
    // Generate n random numbers
    for (let i = 0; i < numOfChosen; i++) {
        let randomNumber;
        do {
            randomNumber = Math.floor(Math.random() * (countriesNum + 1));
        } while (chosenNums.includes(randomNumber)); // Ensure the number is unique
        chosenNums.push(randomNumber);
    }
  
    const img1 = data.results.bindings[chosenNums[0]].imagen_de_la_bandera.value
    const img2 = data.results.bindings[chosenNums[1]].imagen_de_la_bandera.value
    const img3 = data.results.bindings[chosenNums[2]].imagen_de_la_bandera.value
    const img4 = data.results.bindings[chosenNums[3]].imagen_de_la_bandera.value

    const dataString = JSON.stringify(data, null, 2);
    
    const imgElem1 = $("<img>").attr('src',img1);
    const imgElem2 = $("<img>").attr('src',img2);
    const imgElem3 = $("<img>").attr('src',img3);
    const imgElem4 = $("<img>").attr('src',img4);
    console.log(img1)
    console.log(img2)
    console.log(img3)
    console.log(img4)

    $("section:first").append(imgElem1);
    $("section:first").append(imgElem2);
    $("section:first").append(imgElem3);
    $("section:first").append(imgElem4);

    const dataElement = $("<pre>").text(dataString);
    $("section:nth-of-type(2)").append(dataElement);
  }
}

const wiq_api = new WIQ_API();
export {wiq_api}
```

This is the html:

```
<!DOCTYPE HTML>
<html lang="en">
<head>
 <meta charset="UTF-8" />
 <title>WIQ - test</title>
 <meta name ="viewport" content ="width=device-width, initial-scale=1.0" />
 <link rel="stylesheet" type="text/css" href="wiq.css" />
 <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
 
</head>
<body>
 <header>
 <h1>WIQ Game test</h1>
</header>
<section></section>
<section></section>
</body>

<script type="module">
    import {wiq_api} from './wiq.mjs';
    (async () => {
        await wiq_api.getCountriesWithImages();
    })();
</script>
</html> 
```

(And the css just puts the images in a row)

These are two examples of results I got:
![Quests Flags 1](https://github.com/Arquisoft/wiq_en1a/assets/157963970/1c6ec8e2-39e4-4f78-ac5b-085502b7dde2)
![Quests Flags 2](https://github.com/Arquisoft/wiq_en1a/assets/157963970/2f82bf9d-ecbc-404f-baa5-1b7d92bffa66)

The only problem with the code is that sometimes the chosen country does not have a flag image, but that will be easily solved.

About what the service is going to do, I thought about having several methods, one for each type of question and each of them will retrieve a json object (or any type of object) with the information of the question for later construction in the view. The information contained in that object would be the question wording, the correct answer, the wrong ones and maybe the worth of answering correctly/failing. Each method will be documented to know its purpose and what are their parameters and return elements so the person that uses the service has a clear understanding without having to read the code/know how it works.

**Comment by andrrsin** [comment]
This looks amazing Christian. Great Job, finally the deployment occurs :P, so I hope for next week we have a beautiful web to use this. GreatJob. which will be the name of the microservice? Perhaps we want a unique API fo rquestiosn or one for each category! let me know :)

**Comment by UO287621** [comment]
Closing as we have solved this. Obtaninig questions is no longer a problem thanks to Christian :)
