### ISSUE TITLE
Accessing database

### ISSUE THREAD

**Issue by UO287621** [Arquisoft/wiq_en1a#36]
We need the **url** to the mongodb database to connect and a description of the models it has until now

**Comment by uo287841** [comment]
### MongoDB Connection String
mongodb+srv://admin:wiqadm@cluster0.tiaeutl.mongodb.net/

### Connecting with MongoDB Driver
Run this command: npm install mongodb
mongodb+srv://admin:wiqadm@cluster0.tiaeutl.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

**Comment by UO287621** [comment]
closing as we will be using a local database instead of a cloud database
