### ISSUE TITLE
Sending answer to the API

### ISSUE THREAD

**Issue by UO287621** [Arquisoft/wiq_en1a#53]
I've been trying to send the answered question to the API and read it on the backend to process it, but not success yet. Maybe we could change the method to POST instead of GET to send the answer in the body more properly. 
Anyway, we should be able to let the user send the answer to the API. Currently it works on Postman, but not on React page

**Comment by ChristianFN2** [comment]
Yes, using post is more appropriate, I will change that and send a new pull request

**Comment by UO287621** [comment]
Finally fixed this bug, I had to change the request **content type** to `text/plain` in the **axios post** to the question service
