### ISSUE TITLE
Bug with flags

### ISSUE THREAD

**Issue by adriiglz** [Arquisoft/wiq_en1a#56]
Sometimes the app crashes when trying to acces the value property of the flag image: 
```
wiq_en1a\questionservice\question-service.js:64
        imgs.push(data.results.bindings[chosenNums[i]].imagen_de_la_bandera.value)

**Comment by ChristianFN2** [comment]
Yes, that may be a problem with how I checked for the precence of the img in the country element from wikidata, I think the syntax is not what I intended to check. I will test it and send a pr correcting it

**Comment by adriiglz** [comment]
Closing as this was fixed in #57

**Comment by ChristianFN2** [comment]
We have found a way to filter the problem in the query instead of through the code

**Comment by uo287841** [comment]
Code to search for not null flags:

`SELECT ?país ?paísLabel ?imagen_de_la_bandera WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
  ?país wdt:P31 wd:Q6256;
         wdt:P41 ?imagen_de_la_bandera.
  FILTER NOT EXISTS { ?país wdt:P41 wd:Q3024110 }
}`

**Comment by ChristianFN2** [comment]
I will make a pull request later using that query instead, as it is cleaner and more flexible, thanks
