### ISSUE TITLE
2. Architecture Constraints & 1.3 Stakeholders

### ISSUE THREAD

**Issue by uo287841** [Arquisoft/wiq_en1a#7]

**Comment by andrrsin** [comment]
### Comments from the review of Documentation
Once the first review was done, the main proposals of Pablo were:
- Add Wikidata as a Constriant
- There are Constraints that aren't (e.g. javascript, nodejs, etc)
- Do not copy/paste from past years (SOLID) and other.

**Comment by andrrsin** [comment]
### Comments from the review of Documentation
Another point related to the 1.3 is, reviewing the Busines to rephrase it. Perhaps Students also should have new name(devs)
