### ISSUE TITLE
Deployment fix

### ISSUE THREAD

**Issue by andrrsin** [Arquisoft/wiq_en1a#70]
# D1. Problem with microservices not connecting
This problem is regarding the general Deployment, where docker images are generated in the virtual machine, however there is no connectivity between the back end and frontend. I believe the auth and user service does work, the problem is regarding question service.

# D2. GH Actions reinsert Testing
It is important that when running GH Actions, if there are no tests we  should comment the actions regarding them as eventhough the deployment would work, the Action appears as failed. this is not relevant anymore, as the project will need testing from now on.

**Comment by adriiglz** [comment]
D1 was fixed with pull request #71 by @andrrsin

**Comment by andrrsin** [comment]
D2, has been applied in #71 thanks to the help of the teacher. Therefore I proceed to close the issue
