### ISSUE TITLE
New category of questions proposals

### ISSUE THREAD

**Issue by ChristianFN2** [Arquisoft/wiq_en1a#72]
Post here your proposals, try to be simple but interesting

**Comment by ChristianFN2** [comment]
I think an idea would be having several categories of questions all based on images. 

For example we could have the flag questions we now have and also another with players of any concrete sport and the teams they belong to, or movies and the author they belong to, etc.

For that I will need to refactor the code of the flags to be more generic to be able to add more endpoints much easier and not repeat code. Most likely I will have to refactor the wikidata query to gain that flexibility.

I will open a refactoring issue for this matter and post the update there when I am able to.

**Comment by ChristianFN2** [comment]
Another thing that I saw it is possible to do is inserting youtube videos. Wikidata stores the Youtube ids of videos which basically allow us to get the link to the video, and it is possible, as I said, to show it in the front without any additional tool (only html as far as I know)

One idea using this would be getting from wikidata one random song, showing it in the screen (Or maybe, if it is possible, only provide the audio) and then putting as options several singers, one of which would be correct. 
The only problem I see with this is people knowing which song/author it is from the own video, that is why I thought about audio only.

**Comment by ChristianFN2** [comment]
I have prepared some more categories appart from the one introduced in #79 (Yet to be reviewed at this moment), these are 'Guess the fruit', 'Guess the monument', 'Guess the picture', 'Guess the food' and 'Guess the tourist attraction'. I will introduce them if there is no problem with the mentioned pull request so we have 7 categories in total for the image type questions.

**Comment by adriiglz** [comment]
I think the idea of implementing photo-based quenstions fits perfectly our project and lets us extend questions cathegories easily. Regarding the songs, we would have to check how audio works in the frontend, currently I'm designing it but still don't have the knowledge for implementing audio.

Regarding cathegories, I find all you have proposed fine for our project. In addition, we should decide if all those cathegories will score the same points. For example, pictures can score more points per correct answer than monuments

**Comment by adriiglz** [comment]
So these will be the cathegories for this delivery. Closing this issue but we might reopen it in the future if we decide to include new cathegories in next delivery

**Comment by uo287841** [comment]
We could add a Ranfom category that pick a random category between the ones we have
