### ISSUE TITLE
Upload Documentation Plan

### ISSUE THREAD

**Issue by uo287841** [Arquisoft/wiq_en1a#77]
We need a plan to update documentation, there are some points that we have all have worked with and we could assign one in charge of updating them (for instance the first points) or keep it like we have been doing until now.

**Comment by ChristianFN2** [comment]
I propose that, for next Monday and as @uo287841  and I have most of the workload for this week, @adriiglz and @andrrsin could take charge of refining and completing the documentation to not forget about it and reflect better the state of the project

**Comment by adriiglz** [comment]
I still think a dedicated branch for Documentation is the best option, like gh_pages branch
