### ISSUE TITLE
HTTP Request Status

### ISSUE THREAD

**Issue by andrrsin** [Arquisoft/wiq_en1a#80]
Hello!
I just want to remark the importance of sending the correct status on the http requests, as this helps the front end to understand if there is an aerror in the server side. For example here in question--service,js
```js
app.get('/flags/question', async (req, res) => {
  const question = JSON.parse(await wiq.getQuestionAndCountryFlags());
  res.json(question);
});
```
I would recommend to refactor it to:
```js
app.get('/flags/question', async (req, res) => {
    try{
        const question = JSON.parse(await wiq.getQuestionAndCountryFlags());
        res.status(200).json(question);
     } catch(error){
        res.status(400).json({ error: error.message });
}
});
```

I find this a really important thing to do on our API and we can find the main http status codes here [linked](https://developer.mozilla.org/es/docs/Web/HTTP/Status).

**Comment by andrrsin** [comment]
When adding the status codes to the request `/imgs/answer`. As there is not an implemented way to handle api error codes. The game stops when failing the answer. We have to decide wheter we should finish the game here, or just let it continue and implement it.

**Comment by adriiglz** [comment]
Thanks @andrrsin , I will beware of the status codes from now on
