### ISSUE TITLE
Storage of the answer of the question

### ISSUE THREAD

**Issue by ChristianFN2** [Arquisoft/wiq_en1a#84]
## Problem
When we first discussed about how the answer should be produced, we decided to not send the correct answer to the client (so it is not visible through inspection) and delegate the evaluation to the service, which I did by storing the correct answer as a global variable in the server.

The problem with this approach is that, as we will have multiple concurrent users, this will not be operable as if user1 asked for answer validation just after user2 asked for an answer, the answer for user1 will be validated against the question of user2, which is not expected.

## Proposed solutions
- Store the correct answer and its question in the database temporarilly until it is validated (Then removed) (Maybe also store the user id just to cover the remote but possible case two generated questions are the same?)
- Send the encrypted (with a secret key in the server) correct answer to the client in the question and require the client to send both the encrypted and the chosen answer to the answer validating endpoint so it can be decrypted and compared.

## Chosen solution (for now)
As we talked in class I will opt to try to implement the first solution. I think it is better for the API, as the client does not need to send the encrypted password for validating the answer and it is more intuitive. However, the chosen approach increases the number of accesses to the database and could potentially increase response times (Significance will have to be evaluated in load tests)

**Comment by andrrsin** [comment]
I completely agree with you Christian! I believe we can even leave the question stored with a userId and not eliminating them. So we could have a history of questions answered :)

**Comment by adriiglz** [comment]
Data bases are supposed to store elements for a large period of time, they might not be very efficient for recurrent add/delete operations.
Maybe we can use an array or a set inside the service, which can be faster if we just want to use it as a temporal memory

**Comment by ChristianFN2** [comment]
Yes, that is true. I had then thought about keeping the question-answer documents and not deleting them, however, there still will be the need for querying to the database, which might be unnecessarily taxing with enough concurrent users and we do not really need to have a permanent storage in this case as of now, so your proposed solution is simpler and faster. I will implement it and link the corresponding pull request to this issue, thanks.
